-
  color: true
  enable: true
  level: debug
  type: console
-
  enable: true
  file_name: gmaintain.log
  file_path: /var/log
  level: debug
  max_lines: 3000
  max_size: 3M
  type: file
-
  enable: true
  file_name: gmaintain-sql.log
  file_path: /var/log
  level: info
  max_lines: 3000
  max_size: 3M
  type: file
